apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: qqx945taj-nodejs-gitops
  description: This is GitOps manifest for qqx945taj-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=qqx945taj-nodejs
    backstage.io/kubernetes-id: qqx945taj-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: qqx945taj-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:qqx945taj-nodejs
